---
- name: "Deploy WP site"
  hosts: web
  remote_user: vagrant

  vars:
    project: "{{ wordpress_sites[site] }}"
    project_root: "{{ www_root }}/{{ site }}"
    project_deploy_strategy: git
    project_git_repo: "{{ project.repo }}"
    project_version: master
    project_has_composer: true
    project_composer_binary: composer
    project_templates:
      - name: ".env config"
        src: "roles/wordpress-deploy/templates/env.j2"
        dest: ".env"
    project_shared_children:
      - path: "/web/app/uploads"
        src: "uploads"

  roles:
     - f500.project_deploy
