---
- name: "Deploy WP site"
  hosts: web
  remote_user: vagrant

  vars:
    site: "{{ wordpress_sites[site] }}"
    project_root: "{{ www_root }}/{{ site }}"
    project_deploy_strategy: git
    project_git_repo: "{{ site.repo }}"
    project_version: master

  roles:
     - f500.project_deploy
