---
- name: "WordPress Server: Install LEMP Stack with PHP 5.6 and MariaDB MySQL"
  hosts: web
  sudo: yes
  remote_user: admin

  roles:
    - { role: common, tags: [common] }
    - { role: fail2ban, tags: [fail2ban] }
    - { role: ferm, tags: [ferm] }
    - { role: mariadb, tags: [mariadb] }
    - { role: php, tags: [php] }
    - { role: nginx, tags: [nginx] }
    - { role: memcached, tags: [memcached] }
    - { role: composer, tags: [composer] }
    - { role: wp-cli, tags: [wp-cli] }
    - { role: wordpress-setup, tags: [wordpress, wordpress-setup] }
    - { role: wordpress-deploy, tags: [wordpress, deploy, wordpress-deploy] }
    - { role: wordpress-install, tags: [wordpress, wordpress-install] }
